---
# SPDX-License-Identifier: copyleft-next-0.3.1
- name: Get OS-specific variables
  ansible.builtin.include_vars: "{{ lookup('ansible.builtin.first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - default.yml
      paths:
        - "vars"

- name: Enable the CodeReady repo
  ansible.builtin.include_role:
    name: codereadyrepo

- name: Enable installation of packages from EPEL
  ansible.builtin.include_role:
    name: epel-release
  when:
    - ansible_facts['distribution'] != "Fedora"

- name: Add dump package to packages list
  ansible.builtin.set_fact:
    packages: "{{ packages + ['dump'] }}"
  when: >-
    ansible_facts['distribution'] != 'RedHat' or
    ansible_facts['distribution_major_version']|int < 10

- name: Install build dependencies for fstests
  become: true
  become_method: sudo
  ansible.builtin.dnf:
    update_cache: true
    name: "{{ packages }}"
  retries: 3
  delay: 5
  register: result
  until: result is succeeded

- name: Install xfsprogs-xfs_scrub
  become: true
  become_method: sudo
  ansible.builtin.dnf:
    update_cache: true
    name: "{{ packages }}"
  retries: 3
  delay: 5
  register: result
  until: result is succeeded
  vars:
    packages:
      - xfsprogs-xfs_scrub
  when:
    - (ansible_facts['distribution'] != 'RedHat' and ansible_facts['distribution'] != 'CentOS') or ansible_facts['distribution_major_version']|int >= 9

- name: Install btrfs-progs
  become: true
  become_method: sudo
  ansible.builtin.dnf:
    update_cache: true
    name: "{{ packages }}"
  retries: 3
  delay: 5
  register: result
  until: result is succeeded
  vars:
    packages:
      - btrfs-progs
  when: ansible_facts['distribution'] == 'Fedora'

- name: Install dependencies for building xfsprogs
  become: true
  become_flags: "su - -c"
  become_method: sudo
  ansible.builtin.dnf:
    name: "{{ packages }}"
    enablerepo: "*"
  retries: 3
  delay: 5
  register: result
  until: result is succeeded
  vars:
    packages:
      - inih-devel
      - libedit-devel
      - libicu-devel
      - lvm2-devel
      - userspace-rcu-devel
      - device-mapper-devel
      - device-mapper-event-devel
      - libselinux-devel
      - libsepol-devel
      - pcre2-devel
      - gcc-c++
  when: "fstests_xfs_build_custom_xfsprogs|bool"
