- name: Import optional extra_args file
  include_vars: "{{ item }}"
  ignore_errors: yes
  with_first_found:
    - files:
      - "../extra_vars.yml"
      - "../extra_vars.yaml"
      - "../extra_vars.json"
      skip: true
  tags: vars

- name: Set the path where we collect our local pynfs results
  set_fact:
    pynfs_workflow_dir: "../workflows/pynfs"
    pynfs_results_full_path: "{{ topdir_path }}/workflows/pynfs/results"
    pynfs_results_target: "../workflows/pynfs/results/last-run/"
  tags: [ 'vars' ]

- name: Clean up our localhost results directory and files
  local_action: file path="{{ pynfs_workflow_dir }}/results/" state=absent
  run_once: true
  tags: [ 'clean_local_results' ]

- name: Create the local results directory
  local_action: file path="{{ pynfs_workflow_dir }}/results/" state=directory
  run_once: true
  tags: [ 'first_run' ]

- include_role:
    name: create_data_partition
  tags: [ 'data_partition' ]

# Distro specific
- name: Install dependencies
  include_tasks: install-deps/main.yml

- name: Remove old pynfs dir as we always clone a fresh tree
  tags: [ 'git', 'pynfs' ]
  become: yes
  become_flags: 'su - -c'
  become_method: sudo
  file:
    path: "{{ pynfs_data }}"
    state: absent

- name: Shallow-clone the pynfs source code from {{ pynfs_git }}
  tags: [ 'git', 'pynfs' ]
  git:
    repo: "{{ pynfs_git }}"
    dest: "{{ pynfs_data }}"
    update: yes
    version: "{{ pynfs_git_tag }}"
    depth: 1
  retries: 3
  delay: 5
  register: result
  until: not result.failed
  when:
    - kdevops_workflows_dedicated_workflow|bool

- name: Clone the full pynfs source code tree from {{ pynfs_git }}
  tags: [ 'git', 'pynfs' ]
  git:
    repo: "{{ pynfs_git }}"
    dest: "{{ pynfs_data }}"
    update: yes
    version: "{{ pynfs_git_tag }}"
  retries: 3
  delay: 5
  register: result
  until: not result.failed
  when:
    - not kdevops_workflows_dedicated_workflow|bool

- name: Build pynfs
  tags: [ 'pynfs' ]
  command: ./setup.py build
  args:
    chdir: "{{ pynfs_data }}"

- name: Get the hostname of the NFS server and base volname
  tags: [ 'vars' ]
  set_fact:
    nfsd_hostname: "{{ kdevops_host_prefix }}-nfsd"
    volname_base: "pynfs"

- name: Create an export for NFSv4.0 testing
  tags: [ 'pynfs' ]
  include_role:
    name: nfsd_add_export
  vars:
    server_host: "{{ nfsd_hostname }}"
    export_volname: "{{ volname_base }}-4.0"
    export_options: "{{ nfsd_export_options }}"
    export_fstype: "{{ nfsd_export_fstype }}"
    export_size: 10g

- name: Create an export for NFSv4.1 testing
  tags: [ 'pynfs' ]
  include_role:
    name: nfsd_add_export
  vars:
    server_host: "{{ nfsd_hostname }}"
    export_volname: "{{ volname_base }}-4.1"
    export_options: "{{ nfsd_export_options }}"
    export_fstype: "{{ nfsd_export_fstype }}"
    export_size: 10g

- name: Create an export for pNFS testing
  tags: [ 'pynfs' ]
  include_role:
    name: nfsd_add_export
  vars:
    server_host: "{{ nfsd_hostname }}"
    export_volname: "{{ volname_base }}-pnfs"
    export_options: "{{ nfsd_export_options }}"
    export_fstype: "xfs"
    export_size: 10g
    export_pnfs: true
  when:
    - pynfs_pnfs_block|bool

- name: Wait until nfsd grace period ends
  tags: [ 'run_tests' ]
  delegate_to: "{{ nfsd_hostname }}"
  command: /usr/bin/grep -q Y /proc/fs/nfsd/v4_end_grace
  register: result
  retries: 90
  delay: 1
  until: result.rc == 0

- name: Clean up our localhost results/last-run directory
  local_action: file path="{{ pynfs_results_target }}/" state=absent
  run_once: true
  tags: [ 'run_tests', 'copy_results', 'clean_local_results' ]

- name: Create empty last-run directory
  local_action: file path="{{ pynfs_results_target }}/" state=directory
  run_once: true
  tags: [ 'run_tests', 'copy_results', 'clean_local_results' ]

- name: Run pynfs
  tags: [ 'run_tests' ]
  script: "{{ pynfs_workflow_dir }}/scripts/run_pynfs.sh"
  environment:
    PYNFS_DATA: "{{ pynfs_data }}"
    EXPORT_BASE: "{{ nfsd_hostname }}:{{ nfsd_export_path }}/{{ volname_base }}"
    ANSIBLE_HOST: "{{ ansible_host }}"

- name: Run pynfs pNFS block tests
  tags: [ 'run_tests' ]
  script: "{{ pynfs_workflow_dir }}/scripts/run_pynfs_block.sh"
  environment:
    PYNFS_DATA: "{{ pynfs_data }}"
    EXPORT_BASE: "{{ nfsd_hostname }}:{{ nfsd_export_path }}/{{ volname_base }}"
    ANSIBLE_HOST: "{{ ansible_host }}"
  when:
    - pynfs_pnfs_block|bool

- name: Get used target kernel version
  tags: [ 'copy_results' ]
  command: "uname -r"
  register: uname_cmd

- name: Store kernel_rev variable
  tags: [ 'copy_results' ]
  set_fact:
    kernel_rev: "{{ uname_cmd.stdout_lines | regex_replace('\\]') | regex_replace('\\[') | replace(\"'\",'') }}"
  run_once: true

- name: Document used target kernel version
  local_action: "shell echo {{ kernel_rev }} > {{ pynfs_results_target }}/../last-kernel.txt"
  tags: [ 'run_tests', 'copy_results', 'print_results' ]
  run_once: true

- name: Copy the version-specific results to the control node
  tags: [ 'copy_results' ]
  become: yes
  become_flags: 'su - -c'
  become_method: sudo
  fetch:
    src: "{{ pynfs_data }}/pynfs-{{ item }}-results.json"
    dest: "{{ pynfs_results_full_path }}/last-run/{{ kernel_rev}}/{{ kernel_rev }}-v{{ item }}.json"
    flat: yes
  with_items:
    - 4.0
    - 4.1

- name: Copy the pNFS results to the control node
  tags: [ 'copy_results' ]
  become: true
  become_flags: 'su - -c'
  become_method: ansible.builtin.sudo
  fetch:
    src: "{{ pynfs_data }}/pynfs-{{ item }}-results.json"
    dest: "{{ pynfs_results_full_path }}/last-run/{{ kernel_rev}}/{{ kernel_rev }}-v{{ item }}.json"
    flat: true
  with_items:
    - block
  when:
    - pynfs_pnfs_block|bool

- name: Verify last-run kernel directory exists
  tags: [ 'copy_results' ]
  delegate_to: localhost
  stat:
    path: "{{ pynfs_results_full_path }}/last-run/{{ kernel_rev }}"
  register: last_run_kernel_dir

- name: Copy over the last-run into the results directory for archiving into kdevops
  copy:
    src: "{{ pynfs_results_full_path }}/last-run/{{ kernel_rev }}"
    dest: "{{ pynfs_results_full_path }}/"
  run_once: true
  tags: [ 'copy_results' ]
  delegate_to: localhost
  when:
    - last_run_kernel_dir.stat.exists
