---
packages:
  - bison
  - flex
  - git-core
  - automake
  - gcc
  - libuuid
  - libuuid-devel
  - quota
  - make
  - xfsprogs
  - xfsprogs-devel
  - xfsdump
  - e2fsprogs
  - gawk
  - util-linux
  - uuid
  - libuuid-devel
  - acl
  - bc
  - indent
  - libtool
  - lvm2
  - psmisc
  - sed
  - libacl
  - libacl-devel
  - libaio
  - libaio-devel
  - attr
  - libattr-devel
  - openssl-devel
  - ca-certificates
  - libcap
  - gdbm-libs
  - fio
  - dbench
  - e2fsprogs-devel
  - libblkid-devel
  - libzstd-devel
  - libudev-devel
  - python3-devel
  - lzo-devel
  - parted
  - nfs-utils
  - liburing-devel
  - cifs-utils
  - duperemove
  - gettext
  - ncurses
  - ncurses-devel
  - python3-bcc
